"""Add description to podcast

Revision ID: 2734d721d36a
Revises: a6d71f2e7274
Create Date: 2023-03-16 14:18:05.157482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2734d721d36a'
down_revision = 'a6d71f2e7274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
