"""initial migration

Revision ID: 4bc6ecf8f182
Revises: 06e89d6f6fb7
Create Date: 2023-03-19 15:19:30.992746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc6ecf8f182'
down_revision = '06e89d6f6fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genre_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('podcast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_podcast_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_podcast_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_podcast_genre_id'), ['genre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_podcast_title'), ['title'], unique=False)

    op.create_table('episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('podcast_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episode_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_episode_podcast_id'), ['podcast_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_episode_title'), ['title'], unique=False)

    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('podcast_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_podcast_id'), ['podcast_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_user_id'))
        batch_op.drop_index(batch_op.f('ix_rating_podcast_id'))

    op.drop_table('rating')
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episode_title'))
        batch_op.drop_index(batch_op.f('ix_episode_podcast_id'))
        batch_op.drop_index(batch_op.f('ix_episode_created_at'))

    op.drop_table('episode')
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_podcast_title'))
        batch_op.drop_index(batch_op.f('ix_podcast_genre_id'))
        batch_op.drop_index(batch_op.f('ix_podcast_created_at'))
        batch_op.drop_index(batch_op.f('ix_podcast_author_id'))

    op.drop_table('podcast')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genre_name'))

    op.drop_table('genre')
    # ### end Alembic commands ###
